name: Tauri Build & Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        platform: [macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装 Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: |
            x86_64-apple-darwin
            aarch64-apple-darwin
            x86_64-pc-windows-msvc

      - name: 安装 Windows 依赖（手动安装 Wix）
        if: matrix.platform == 'windows-latest'
        run: |
          Invoke-WebRequest -Uri "https://github.com/wixtoolset/wix3/releases/download/wix3111rtm/wix311.exe" -OutFile "C:\wix311.exe"
          Start-Process -FilePath "C:\wix311.exe" -ArgumentList "/quiet" -NoNewWindow -Wait
          echo "C:\Program Files (x86)\WiX Toolset v3.11\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: 安装 macOS 交叉编译工具
        if: matrix.platform == 'macos-latest'
        run: |
          brew install zig
          cargo install cargo-zigbuild

      - name: 安装 Tauri CLI
        run: cargo install tauri-cli

      - name: 构建应用
        run: cargo tauri build

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: Tauri-Build-${{ matrix.platform }}
          path: |
            src-tauri/target/release/bundle/**/*
